version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - VIRTUAL_HOST=htb.penalosa.dev
      - LETSENCRYPT_HOST=htb.penalosa.dev
  mongo:
    image: mongo
    ports:
      - "27017:27017"
